# Generated by Django 4.0.2 on 2023-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
